on:
  push:
    branches:
      - master
      - main

jobs:
  tag:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag -a v${{ github.run_number }} -m "Tag v${{ github.run_number }}"
          git push origin v${{ github.run_number }}
